services:
  db:
    image: postgres:15-alpine
    container_name: ejc_hub_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ejc_hub
      POSTGRES_PASSWORD: ejc_hub
      POSTGRES_DB: ejc_hub
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d

volumes:
  db_data:
