services:
  db:
    image: bitnami/postgresql:latest
    container_name: ejc_hub_database
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ejc_hub
      POSTGRES_PASSWORD: ejc_hub
      POSTGRES_DB: ejc_hub
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
